### ISSUE TITLE
Where should our email templates be stored?

### ISSUE THREAD

**Issue by idmontie** [gios-asu/grunt-email-workflow#1]
Some choices:
- WordPress pages
- In a separate repo (i.e this repo)
- In Gios API

I'd think the easiest way would be in this repo, that way all repos are centralized and the Gios API just requires this repo be checked out on the server.

@gios-asu/informatics What do you think?

**Comment by rraub** [comment]
As discussed another option is in the database, but right now I'm leaning towards file repo based solution. To be discussed further is how to get dynamic data from the database and use that in the email template?

**Comment by idmontie** [comment]
This will be its own repo with the email templates contained within.  The repo will also have ruby script that will take in data and build an email from the template.  The database will contain all of the colors and email series information.
