### ISSUE TITLE
Integrating into Ruby

### ISSUE THREAD

**Issue by idmontie** [gios-asu/grunt-email-workflow#2]
We should be able to run the whole pipeline through ruby.  Here is a rough idea:
1. When an event is saved, run the pipeline.
2. Compile SCSS to CSS using Ruby.
   
    We can do this by using the [Sass Engine](http://sass-lang.com/documentation/Sass/Engine.html):

``` ruby
template = File.load('this/repos/path/src/css/scss/main.scss')
template.prepend(scssColors)
sass_engine = Sass::Engine.new(template, {
  :syntax => :scss,
  :load_paths => ['this/repos/path/src/css/scss']
})
css = sass_engine.render #=> "* {\n  font-family: "Helvetica Neue", "Helvetica", Helvetica, Arial, sans-serif;..."
```

The compiled CSS is now in memory.
1. Compile Handlebars using [Handlebars.rb.](https://github.com/cowboyd/handlebars.rb)

``` ruby
require 'handlebars'
handlebars = Handlebars::Context.new
template = File.load('this/repos/path/src/emails/generic-email-template.hbs')
handle = handlebars.compile(template)
pre_html = handle.call(
  :site_url => "http://sustainability.asu.edu",
  :event_name => event.name
) #=> "<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\n ..."
```
1. Inline the CSS from step 2 with the HTML generated in step 3 with [Premailer](https://github.com/premailer/premailer).

``` ruby
require 'premailer'

premailer = Premailer.new(pre_html, {
  :with_html_string => true,
  :css_string => css,
})

html = premailer.to_inline_css
text = premailer.to_plain_text
```

**Comment by rraub** [comment]
sounds good to me, we should try this out in a rails app

**Comment by idmontie** [comment]
See https://github.com/gios-asu/wordpress-newsletter-plugin

**Comment by idmontie** [comment]
No longer really need to integrate this into ruby, unless we compile the email when an event is saved
